export type BriefInfluencersViewTranslation = {
    edit_brief: string;
    default_Brief: string;
    select_types: string;
    post: string;
    story: string;
    video: string;
    number_posts: string;
    number_stories: string;
    number_videos: string;
    offer: string;
    offer_placeholder: string;
    requirements_guidelines_restrictions: string;
    requirements_placeholder: string;
    share_vision_creatives: string;
    share_vision_placeholder: string;
    special_hashtags: string;
    hashtags_placeholder: string;
    special_mentions: string;
    mentions_placeholder: string;
    special_notes: string;
    notes_placeholder: string;
    invite_influencer: string;
    create_default_brief: string;
    references_terms_contracts: string;
};
