export type BriefDetailViewTranslation = {
    invited_collaborate: string;
    contacts: string;
    messages: string;
    decline: string;
    accept: string;
    waiting: string;
    dates: string;
    posts: string;
    stories: string;
    videos: string;
    offer: string;
    campaign_name: string;
    hashtags: string;
    mentions: string;
    requirements_guidelines: string;
    vision_other: string;
    special_notes: string;
    accepted: string;
};
