export type DashboardTranslation = {
    dashboard: string;
    campaign: string;
    campaign_pl: string;
    profile: string;
    title: string;
    date_range: string;
    objectiveTitle: string;
    influencers: string;
    posts: string;
    stories: string;
    videos: string;
    budget: string;
    edit: string;
    delete: string;
    new_campaign: string;
    message_influencer: string;
    message_manager: string;
    go_to_profile: string;
};
