import { AddInfluencersTranslation } from './add_influencers';
import { BriefDetailViewTranslation } from './brief_detail';
import { BriefInfluencersViewTranslation } from './brief_influencers';
import { CampaignDetailTranslation } from './campaign_detail';
import { CategoriesTranslation } from './categories';
import { ChangePasswordTranslation } from './change_password';
import { ConnectTransl } from './connect';
import { CreateCampaignTranslation } from './create_campaign';
import { CreateOrganizationTranslation } from './create_organization';
import { CreativesTranslation } from './creatives';
import { CreativesUploadEditTranslation } from './creatives_upload_edit';
import { DashboardTranslation } from './dashboard';
import { ErrorMessagesTranslation } from './error_messages';
import { FooterTranslation } from './footer';
import { HeaderTranslation } from './header';
import { InfluencerCardTranslation } from './influencer_card';
import { InfluencerProfileTranslation } from './influencer_profile';
import { InvitationStartTranslation } from './invitation_start';
import { LoginTranslation } from './login';
import { MarketplaceTranslation } from './marketplace';
import { MonthsTranslation } from './months';
import { RegisterTranslation } from './registration';
import { RegisterSuccessTranslation } from './registration_success';
import { SupportTranslation } from './support';
import { ThermsTranslation } from './therms';
import { UpdateAccTranslation } from './update_acc';

export type SupportedLanguages = 'en' | 'es' | 'bg';

export type LanguageTypes = {
    language: SupportedLanguages;
    registration: RegisterTranslation;
    registration_success: RegisterSuccessTranslation;
    connect: ConnectTransl;
    therms: ThermsTranslation;
    // general: {}
    creatives: CreativesTranslation;
    login: LoginTranslation;
    dashboard: DashboardTranslation;
    marketplace: MarketplaceTranslation;
    influencer_profile: InfluencerProfileTranslation;
    create_campaign: CreateCampaignTranslation;
    create_organization: CreateOrganizationTranslation;
    campaign_detail: CampaignDetailTranslation;
    creatives_upload_edit: CreativesUploadEditTranslation;
    support: SupportTranslation;
    influencer_card: InfluencerCardTranslation;
    footer: FooterTranslation;
    header: HeaderTranslation;
    update_acc: UpdateAccTranslation;
    change_password: ChangePasswordTranslation;
    brief_influencers: BriefInfluencersViewTranslation;
    error_messages: ErrorMessagesTranslation;
    months: MonthsTranslation;
    invitation_start: InvitationStartTranslation;
    brief_detail: BriefDetailViewTranslation;
    add_influencers: AddInfluencersTranslation;
    categories: CategoriesTranslation;
};
