import { Countries } from './countries';

export type UpdateAccTranslation = {
    user_account: string;
    create_organization: string;
    change_password: string;
    name: string;
    name_placeholder: string;
    email: string;
    email_placeholder: string;
    phone_number: string;
    phone_placeholder: string;
    update_profile: string;
    log_out: string;
    bio: string;
    placeholder_bio: string;
    topics: string;
    placeholder_topics: string;
    categories: string;
    channels: string;
    city: string;
    placeholderCity: string;
    country: Countries;
    placeholderCountry: string;
    average_price_for_one_post: string;
    average_price_for_one_story: string;
    average_price_for_one_video: string;
    tooltip_text: string;
    press_enter_tags: string;
    least_one_category: string;
};
